all implemented, but 'adjustment' style reactions (like wall loss) wi…
NCAR/music-box-interactive-api pull request #345
Opened 2023-05-30 19:26 UTC by jacobian-bacon

…th only products and not reactants are graphed as orphan nodes.

2023-05-30 21:28 UTC, K20shores requested changes

2023-05-30 21:28 UTC, K20shores commented on interactive/plots/flow_diagram.py
> +def return_valid_df_time_indices(df, user_time_range, model_timestep):
Please convert all of these comments into [docstrings](https://peps.python.org/pep-0257/#multi-line-docstrings)

2023-05-30 21:28 UTC, K20shores commented on interactive/plots/flow_diagram.py
> +                # logger.info(f"average_flux: {average_flux}")
Please delete commented out code. If it's debug information that could be useful, change the logging level to debug and uncomment

2023-05-31 15:31 UTC, mattldawson approved these changes

2023-06-06 17:36 UTC, merged